<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $v_code == 'index' ? 404 : $v_code; ?> - <?php echo $v_title; ?></title>
	<style type="text/css"><?php echo $css; ?></style>
</head>

<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-285981-14', 'seravo.fi');
  ga('send', 'pageview');

  ga('send', 'event', '<?php echo $v_code == 'index' ? 'no-site' : $v_code; ?>', document.location.host, document.location.pathname);
</script>

	<div class="cover">
    <h1><?php echo $v_code == 'index' ? 404 : $v_code; ?> - <?php echo $v_title; ?></h1>
		<p class="lead"><?php echo $v_message0; ?></p>
		<p class="lead"><?php echo $v_message1; ?></p>
	</div>

	<?php if ($config['footer'] != null){ ?>
	<footer>
		<p><?php echo $config['footer']; ?></p>
	</footer>
	<?php } ?>

</body>
</html>
